apiVersion: v2
name: kafka-server
description: A Helm chart for deploying Apache Kafka server.
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kafka-ui
    version: 0.1.0
    repository: "file://charts/kafka-ui"
